=begin
#Wineshipping API Suite

#Wineshipping API is a programmatically consumable service or an Application Programming Interface (API) suite designed to enable Wineshipping LLC's client applications to natively transmit and manage their order, view inventory, create product, validate address, track shipments etc.<br /><br />In order to access API operations request a user key and password from Wineshipping. For any questions please contact Wineshipping Helpdesk at <a href='mailto:api@wineshipping.com?Subject=API from Wineshipping'>api@wineshipping.com</a>.

OpenAPI spec version: V3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.44
=end

require 'spec_helper'
require 'json'

# Unit tests for WineShipping::BillingApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'BillingApi' do
  before do
    # run before each test
    @instance = WineShipping::BillingApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BillingApi' do
    it 'should create an instance of BillingApi' do
      expect(@instance).to be_instance_of(WineShipping::BillingApi)
    end
  end

  # unit tests for get_invoice_details
  # This method allows a customer to retrieve billing invoices. Billing invoices include Fulfillment, DTT, Storage, Supplemental invoice types. There are multiple input filters available for use, including filters to retrieve specific types of billing invoice, to retrieve invoice processed on a particular date, or to retrieve invoice for a specific Wineshipping warehouse transaction.  There are also pagination and skip/top query parameters that allow customers to further control the invoices that are returned in the response.
  # @param body 
  # @param [Hash] opts the optional parameters
  # @return [InvoiceDetailsResult]
  describe 'get_invoice_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
