=begin
#API from Wineshipping

#Wineshipping API is a programmatically consumable service or an Application Programming Interface (API) platform designed to enable Wineshipping LLC's client applications to natively transmit and manage their order, view inventory, track shipments etc.<br /><br />In order to access API operations request a user key and password from Wineshipping. For any questions please contact Wineshipping Helpdesk at <a href='mailto:IT-Help@wineshipping.com?Subject=API from Wineshipping'>IT-Help@wineshipping.com</a>.

OpenAPI spec version: V3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for WineShipping::SalesOrderApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SalesOrderApi' do
  before do
    # run before each test
    @instance = WineShipping::SalesOrderApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SalesOrderApi' do
    it 'should create an instance of SalesOrderApi' do
      expect(@instance).to be_instance_of(WineShipping::SalesOrderApi)
    end
  end

  # unit tests for create_sales_order
  # Successful execution of this method will generate a new shipment order in Wineshipping&#39;s system and will return a transaction reference identifier. Store this identifier back into your system for reference later in the event there is an issue with your order.
  # @param order_details_info 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_sales_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_orders_on_hold
  # Use this operation to retrieve a list of on-hold orders for a customer. Successful execution of this method will generate a list of on hold orders from Wineshipping&#39;s system and if no orders are on hold, HTTP status code Not Found response will be returned.
  # @param authentication_details 
  # @param [Hash] opts the optional parameters
  # @return [Array<OrderOnHold>]
  describe 'get_orders_on_hold test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_returns
  # Use this operation to retrieve a list of return sales orders for a customer. Successful execution of this method will generate a list of returns from Wineshipping system.
  # @param returns_request_details 
  # @param [Hash] opts the optional parameters
  # @return [ReturnResult]
  describe 'get_returns test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_sales_order
  # Use this operation to update an existing open sales order. Successful execution of this method will update an open sales order in Wineshipping system. If for some reason the order cannot be updated standard HTTP Status Code and a reason will be returned.
  # @param order_details_info 
  # @param [Hash] opts the optional parameters
  # @option opts [BOOLEAN] :is_cancel_only 
  # @return [nil]
  describe 'update_sales_order test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
