=begin
#API from Wineshipping

#Wineshipping API is a programmatically consumable service or an Application Programming Interface (API) platform designed to enable Wineshipping LLC's client applications to natively transmit and manage their order, view inventory, track shipments etc.<br /><br />In order to access API operations request a user key and password from Wineshipping. For any questions please contact Wineshipping Helpdesk at <a href='mailto:IT-Help@wineshipping.com?Subject=API from Wineshipping'>IT-Help@wineshipping.com</a>.

OpenAPI spec version: V3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for WineShipping::SKUApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SKUApi' do
  before do
    # run before each test
    @instance = WineShipping::SKUApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SKUApi' do
    it 'should create an instance of SKUApi' do
      expect(@instance).to be_instance_of(WineShipping::SKUApi)
    end
  end

  # unit tests for create_sku
  # Successful execution of this method will generate a new SKU in Wineshipping&#39;s system and will return a transaction reference identifier. Store this identifier back into your system for reference later in the event there is an issue with the SKU.
  # @param sku_request_details 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_sku test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
