=begin
#Wineshipping API Suite

#Wineshipping API is a programmatically consumable service or an Application Programming Interface (API) suite designed to enable Wineshipping LLC's client applications to natively transmit and manage their order, view inventory, create product, validate address, track shipments etc.<br /><br />In order to access API operations request a user key and password from Wineshipping. For any questions please contact Wineshipping Helpdesk at <a href='mailto:api@wineshipping.com?Subject=API from Wineshipping'>api@wineshipping.com</a>.

OpenAPI spec version: V3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.44
=end

# Common files
require 'wine_shipping/api_client'
require 'wine_shipping/api_error'
require 'wine_shipping/version'
require 'wine_shipping/configuration'

# Models
require 'wine_shipping/models/address'
require 'wine_shipping/models/address_validation_classification_request'
require 'wine_shipping/models/address_validation_classification_result'
require 'wine_shipping/models/authentication'
require 'wine_shipping/models/billing_contact_info'
require 'wine_shipping/models/business_hour'
require 'wine_shipping/models/candidate_address'
require 'wine_shipping/models/candidate_address_format'
require 'wine_shipping/models/carrier_location'
require 'wine_shipping/models/carrier_locations_request'
require 'wine_shipping/models/carrier_locations_result'
require 'wine_shipping/models/create_sales_order_status'
require 'wine_shipping/models/create_sales_orders_result'
require 'wine_shipping/models/customer'
require 'wine_shipping/models/delivery_contact_info'
require 'wine_shipping/models/delivery_estimate_option'
require 'wine_shipping/models/delivery_estimate_request'
require 'wine_shipping/models/delivery_estimate_result'
require 'wine_shipping/models/geographic_coordinates'
require 'wine_shipping/models/inventory_item'
require 'wine_shipping/models/inventory_status_request'
require 'wine_shipping/models/inventory_status_result'
require 'wine_shipping/models/inventory_transaction'
require 'wine_shipping/models/inventory_transaction_request'
require 'wine_shipping/models/inventory_transaction_result'
require 'wine_shipping/models/invoice'
require 'wine_shipping/models/invoice_details_request'
require 'wine_shipping/models/invoice_details_result'
require 'wine_shipping/models/item_info'
require 'wine_shipping/models/line_info'
require 'wine_shipping/models/location_address'
require 'wine_shipping/models/oct_preferred_ship_day_profile'
require 'wine_shipping/models/order_on_hold'
require 'wine_shipping/models/order_on_hold_item'
require 'wine_shipping/models/pal_address'
require 'wine_shipping/models/pal_request'
require 'wine_shipping/models/pal_response'
require 'wine_shipping/models/package'
require 'wine_shipping/models/package_item'
require 'wine_shipping/models/package_tracking_request'
require 'wine_shipping/models/package_tracking_result'
require 'wine_shipping/models/personalization'
require 'wine_shipping/models/purchase_order_cancel_request'
require 'wine_shipping/models/purchase_order_details'
require 'wine_shipping/models/purchase_order_info'
require 'wine_shipping/models/purchase_order_item_info'
require 'wine_shipping/models/recipient_contact_info'
require 'wine_shipping/models/requestor_info'
require 'wine_shipping/models/return_result'
require 'wine_shipping/models/return_sales_order_header'
require 'wine_shipping/models/return_sales_order_line'
require 'wine_shipping/models/returns_request'
require 'wine_shipping/models/sku_details'
require 'wine_shipping/models/sku_info'
require 'wine_shipping/models/sales_order'
require 'wine_shipping/models/sales_order_cancel_request'
require 'wine_shipping/models/sales_order_details'
require 'wine_shipping/models/sales_order_header_info'
require 'wine_shipping/models/sales_order_info'
require 'wine_shipping/models/sales_orders_batch'
require 'wine_shipping/models/sellable_inventory_request'
require 'wine_shipping/models/sellable_inventory_result'
require 'wine_shipping/models/shipment_info'
require 'wine_shipping/models/shipping_option'
require 'wine_shipping/models/tracking_request'
require 'wine_shipping/models/tracking_result'
require 'wine_shipping/models/transfer_info'
require 'wine_shipping/models/transfer_item_info'
require 'wine_shipping/models/transfer_order_cancel_request'
require 'wine_shipping/models/transfer_order_details'
require 'wine_shipping/models/update_sku_details'
require 'wine_shipping/models/update_sku_info'
require 'wine_shipping/models/warehouse_inventory_status'

# APIs
require 'wine_shipping/api/address_api'
require 'wine_shipping/api/billing_api'
require 'wine_shipping/api/inventory_api'
require 'wine_shipping/api/inventory_movement_api'
require 'wine_shipping/api/sku_api'
require 'wine_shipping/api/sales_order_api'
require 'wine_shipping/api/tracking_api'

module WineShipping
  class << self
    # Customize default settings for the SDK using block.
    #   WineShipping.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
