=begin
#Wineshipping API Suite

#Wineshipping API is a programmatically consumable service or an Application Programming Interface (API) suite designed to enable Wineshipping LLC's client applications to natively transmit and manage their order, view inventory, create product, validate address, track shipments etc.<br /><br />In order to access API operations request a user key and password from Wineshipping. For any questions please contact Wineshipping Helpdesk at <a href='mailto:api@wineshipping.com?Subject=API from Wineshipping'>api@wineshipping.com</a>.

OpenAPI spec version: V3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.44
=end

require 'date'

module WineShipping
  class OCTPreferredShipDayProfile
    attr_accessor :idk__backing_field

    attr_accessor :titlek__backing_field

    attr_accessor :mondayk__backing_field

    attr_accessor :tuesdayk__backing_field

    attr_accessor :wednesdayk__backing_field

    attr_accessor :thursdayk__backing_field

    attr_accessor :fridayk__backing_field

    attr_accessor :saturdayk__backing_field

    attr_accessor :sundayk__backing_field

    attr_accessor :notesk__backing_field

    attr_accessor :created_byk__backing_field

    attr_accessor :created_onk__backing_field

    attr_accessor :modified_byk__backing_field

    attr_accessor :modified_onk__backing_field

    attr_accessor :messagek__backing_field

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'idk__backing_field' => :'<Id>k__BackingField',
        :'titlek__backing_field' => :'<Title>k__BackingField',
        :'mondayk__backing_field' => :'<Monday>k__BackingField',
        :'tuesdayk__backing_field' => :'<Tuesday>k__BackingField',
        :'wednesdayk__backing_field' => :'<Wednesday>k__BackingField',
        :'thursdayk__backing_field' => :'<Thursday>k__BackingField',
        :'fridayk__backing_field' => :'<Friday>k__BackingField',
        :'saturdayk__backing_field' => :'<Saturday>k__BackingField',
        :'sundayk__backing_field' => :'<Sunday>k__BackingField',
        :'notesk__backing_field' => :'<Notes>k__BackingField',
        :'created_byk__backing_field' => :'<CreatedBy>k__BackingField',
        :'created_onk__backing_field' => :'<CreatedOn>k__BackingField',
        :'modified_byk__backing_field' => :'<ModifiedBy>k__BackingField',
        :'modified_onk__backing_field' => :'<ModifiedOn>k__BackingField',
        :'messagek__backing_field' => :'<Message>k__BackingField'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'idk__backing_field' => :'Object',
        :'titlek__backing_field' => :'Object',
        :'mondayk__backing_field' => :'Object',
        :'tuesdayk__backing_field' => :'Object',
        :'wednesdayk__backing_field' => :'Object',
        :'thursdayk__backing_field' => :'Object',
        :'fridayk__backing_field' => :'Object',
        :'saturdayk__backing_field' => :'Object',
        :'sundayk__backing_field' => :'Object',
        :'notesk__backing_field' => :'Object',
        :'created_byk__backing_field' => :'Object',
        :'created_onk__backing_field' => :'Object',
        :'modified_byk__backing_field' => :'Object',
        :'modified_onk__backing_field' => :'Object',
        :'messagek__backing_field' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `WineShipping::OCTPreferredShipDayProfile` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `WineShipping::OCTPreferredShipDayProfile`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'idk__backing_field')
        self.idk__backing_field = attributes[:'idk__backing_field']
      end

      if attributes.key?(:'titlek__backing_field')
        self.titlek__backing_field = attributes[:'titlek__backing_field']
      end

      if attributes.key?(:'mondayk__backing_field')
        self.mondayk__backing_field = attributes[:'mondayk__backing_field']
      end

      if attributes.key?(:'tuesdayk__backing_field')
        self.tuesdayk__backing_field = attributes[:'tuesdayk__backing_field']
      end

      if attributes.key?(:'wednesdayk__backing_field')
        self.wednesdayk__backing_field = attributes[:'wednesdayk__backing_field']
      end

      if attributes.key?(:'thursdayk__backing_field')
        self.thursdayk__backing_field = attributes[:'thursdayk__backing_field']
      end

      if attributes.key?(:'fridayk__backing_field')
        self.fridayk__backing_field = attributes[:'fridayk__backing_field']
      end

      if attributes.key?(:'saturdayk__backing_field')
        self.saturdayk__backing_field = attributes[:'saturdayk__backing_field']
      end

      if attributes.key?(:'sundayk__backing_field')
        self.sundayk__backing_field = attributes[:'sundayk__backing_field']
      end

      if attributes.key?(:'notesk__backing_field')
        self.notesk__backing_field = attributes[:'notesk__backing_field']
      end

      if attributes.key?(:'created_byk__backing_field')
        self.created_byk__backing_field = attributes[:'created_byk__backing_field']
      end

      if attributes.key?(:'created_onk__backing_field')
        self.created_onk__backing_field = attributes[:'created_onk__backing_field']
      end

      if attributes.key?(:'modified_byk__backing_field')
        self.modified_byk__backing_field = attributes[:'modified_byk__backing_field']
      end

      if attributes.key?(:'modified_onk__backing_field')
        self.modified_onk__backing_field = attributes[:'modified_onk__backing_field']
      end

      if attributes.key?(:'messagek__backing_field')
        self.messagek__backing_field = attributes[:'messagek__backing_field']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          idk__backing_field == o.idk__backing_field &&
          titlek__backing_field == o.titlek__backing_field &&
          mondayk__backing_field == o.mondayk__backing_field &&
          tuesdayk__backing_field == o.tuesdayk__backing_field &&
          wednesdayk__backing_field == o.wednesdayk__backing_field &&
          thursdayk__backing_field == o.thursdayk__backing_field &&
          fridayk__backing_field == o.fridayk__backing_field &&
          saturdayk__backing_field == o.saturdayk__backing_field &&
          sundayk__backing_field == o.sundayk__backing_field &&
          notesk__backing_field == o.notesk__backing_field &&
          created_byk__backing_field == o.created_byk__backing_field &&
          created_onk__backing_field == o.created_onk__backing_field &&
          modified_byk__backing_field == o.modified_byk__backing_field &&
          modified_onk__backing_field == o.modified_onk__backing_field &&
          messagek__backing_field == o.messagek__backing_field
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [idk__backing_field, titlek__backing_field, mondayk__backing_field, tuesdayk__backing_field, wednesdayk__backing_field, thursdayk__backing_field, fridayk__backing_field, saturdayk__backing_field, sundayk__backing_field, notesk__backing_field, created_byk__backing_field, created_onk__backing_field, modified_byk__backing_field, modified_onk__backing_field, messagek__backing_field].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        WineShipping.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
